# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "slape/ubuntu-dev"
  config.vm.box_version = "1.0"
  config.vm.synced_folder "~", "/Shared/Host-Home"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name = "ubuntu_dev"
    vb.memory = "8192"
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
    vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
    vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "../ansible/main.yml"
  end
end
