---
- name: Download Brave gpg key
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: 0700

- name: Add Brave gpg key to apt
  apt_key:
    file: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    state: present

- name: Add Brave repository into sources list
  apt_repository:
    repo: deb https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present

- name: Install Brave Apt Package
  apt:
    update_cache: yes
    pkg:
      - brave-browser