---
- name: Install Azure CLI gpg key
  ansible.builtin.apt_key:
    state: present
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: Add Azure CLI repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.microsoft.com/repos/azure-cli/ impish main
    state: present

- name: Install Azure CLI Package
  apt:
    update_cache: yes
    auto_update: yes
    pkg:
      - azure-cli