---
# - name: Download Microsoft gpg key
#   get_url:
#     url: https://packages.microsoft.com/keys/microsoft.asc
#     dest: /usr/share/keyrings/microsoft-archive-keyring.gpg
#     mode: 0700

# - name: Add Microsoft gpg key to apt
#   apt_key:
#     file: /usr/share/keyrings/microsoft-archive-keyring.gpg
#     state: present

# - name: Add Azure CLI repository into sources list
#   ansible.builtin.apt_repository:
#     repo: deb https://packages.microsoft.com/repos/azure-cli/ bionic main
#     state: present

# - name: Add VSCode repository into sources list
#   apt_repository:
#     repo: deb https://packages.microsoft.com/repos/vscode stable main
#     state: present

# - name: Install Microsoft CLI Packages
#   apt:
#     update_cache: yes
#     pkg:
#       - azure-cli
#       - code

- name: Install VSCode Extensions
  shell: |
    sudo -H -u vagrant \
    code \
    --install-extension ms-vscode.powershell \
    --install-extension ms-python.python \
    --install-extension vscodevim.vim \
    --install-extension ms-azuretools.vscode-docker \
    --install-extension ms-vscode.azurecli \
    --install-extension shakram02.bash-beautify \
    --install-extension rogalmic.bash-debug \
    --install-extension rebornix.ruby \
    --install-extension hashicorp.terraform \
    --install-extension mohsen1.prettify-json \
    --install-extension redhat.vscode-yaml \
    EOF
