---
- name: Update Ubuntu
  apt:
    force_apt_get: yes
    update_cache: yes
    update_cache_retries: 5
    update_cache_retry_max_delay: 12
    upgrade: yes
    autoclean: yes

- name: Install or upgrade basic Apt packages
  apt:
    update_cache: yes
    install_recommends: yes
    force_apt_get: yes
    pkg:
      - git
      - curl 
      - nmap
      - python3-pip
      - vim
      - wget
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - lsb-release 
      - gnupg
      - tmux
      - ufw
      - whois

- name: Install Discord
  community.general.snap:
    name:
      - discord