---
- name: download hashicorp gpg key
  get_url:  
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-keyring.gpg
    mode: 0700

- name: Install hashicorp gpg key
  apt_key:
    state: present
    file: /usr/share/keyrings/hashicorp-keyring.gpg 

- name: Add hashicorp repository into sources list
  apt_repository:
    repo: deb https://apt.releases.hashicorp.com focal main
    state: present

- name: Install Hashicorp Apt Packages
  apt:
    update_cache: yes
    pkg:
      - terraform
      - packer