---
- name: Download Microsoft gpg key
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /usr/share/keyrings/microsoft-archive-keyring.gpg
    mode: 0700

- name: Add Microsoft gpg key to apt
  apt_key:
    file: /usr/share/keyrings/microsoft-archive-keyring.gpg
    state: present

- name: Add Azure CLI repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.microsoft.com/repos/azure-cli/ bionic main
    state: present

- name: Add VSCode repository into sources list
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: Install Microsoft CLI Packages
  apt:
    update_cache: yes
    pkg:
      - azure-cli
      - code