---
- name: Clean up Apt-get
  apt:
    force_apt_get: yes
    update_cache: yes
    autoclean: yes
    autoremove: yes
    purge: yes

- name: clear bash history for root user
  shell: rm -rf ~/.bash_history

- name: clear bash history for vagrant user
  shell: rm -rf /home/vagrant/.bash_history